[package]
name = "cli"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[dependencies]
# actix-web = "3"
# actix-service = "1.0.6"
# env_logger = "0.7.1"
# futures = "0.3.5"
# structopt = "0.3.17"